name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build_windows_exe:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install tensorflow opencv-python scikit-learn pillow pyinstaller==5.13.0

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --name "image_gui" image_gui.py ^
            --hidden-import=tkinter ^
            --hidden-import=PIL.ImageTk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_gui-exe
          path: dist/image_gui.exe

